[tool.poetry]
name = "grandmom-ai"
version = "0.1.0"
description = ""
authors = ["JEONGMYEONGHONG"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.32.3"
fastapi = "^0.111.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
